### ISSUE TITLE
adonis js typescript server keep dying because of fetch

### ISSUE THREAD

**Issue by mtariqsajid** [Secreto31126/whatsapp-api-js#60]
node version : 18.14.0
whatsapp-api-js : 0.8.2

the adonis 5 server keep dying because of fetch req is not closing 
can you please tell me what should i do to resolve this error

```bash
TypeError: fetch failed
    at fetch (/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/index.js:113:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/lib/core/connect.js:182:24)
      at /home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/lib/core/connect.js:129:46
      at Immediate._onImmediate (/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/lib/core/connect.js:170:9)
      at processImmediate (node:internal/timers:466:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
[22:48:07.069] FATAL (whatsapp-chatgpt/44690): "uncaughtException" detected
    TypeError: fetch failed
        at fetch (/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/index.js:113:13)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
[22:48:07.069] WARN (whatsapp-chatgpt/44690): pino.final with prettyPrint does not support flushing

/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/index.js:113
      Error.captureStackTrace(err, this)
            ^
TypeError: fetch failed
    at fetch (/home/expertscloud/js_projects/whatsapp-chatgpt/node_modules/undici/index.js:113:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ warn ]  Underlying HTTP server died with "1 code"

```

**Comment by Secreto31126** [comment]
Hmm, I think the error is happening outside of the library, but maybe there's a correlation. May I get a snippet of your code to see how you are using it?

**Comment by Secreto31126** [comment]
Is, by any chance, your issue related to https://github.com/nodejs/undici/issues/1531 ? Might be worth trying [this setting](https://github.com/nodejs/undici/issues/1531#issuecomment-1416212916)

**Comment by mtariqsajid** [comment]
I think you are right its related to node 18 DNS, I am now using node 16 let see if issue come up again 

> Is, by any chance, your issue related to [nodejs/undici#1531](https://github.com/nodejs/undici/issues/1531) ? Might be worth trying [this setting](https://github.com/nodejs/undici/issues/1531#issuecomment-1416212916)

**Comment by Secreto31126** [comment]
Closed as stale. Let me know if Node 16 did the trick.
